version: "3.9"
services:
  flask:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2.8-bionic
    volumes:
      - nba-mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  nba-mongo-data: